---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxhello
  name: nginxhello
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/tag.nginxhello: semver:~1.0.x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxhello
  template:
    metadata:
      labels:
        app: nginxhello
    spec:
      containers:
      - image: macprasanna/sample-tomcat:1.0.3
        name: nginxhello
        ports:
        - containerPort: 80
